#!/bin/sh
case "$(printf "lockscreen\\nlogout\\nreboot\\nshutdown" | bemenu)" in
	"lockscreen") swaylock -s fill -i ~/Drive/Media/Pictures/wallpaper.png ;;
	"logout") prompt "logout?" "kill -9 -1" ;;
	"reboot") prompt "reboot computer?" "sudo reboot" ;;
	"shutdown") prompt "shutdown computer?" "sudo shutdown -h now" ;;
esac
